exchange:
  app_id: 6ceeba0719d542b48a78e1d58eb8e959
  base_currency: USD
  base_url: https://openexchangerates.org/api
  currencies_path: /currencies.json
  latest_path: /latest.json
  historical_path: /historical
giphy:
  api_key: Y0atksBSybVGClGyldtudS2Ok29hqMb8
  base_url: api.giphy.com/v1/gifs/random
  positive_tag: rich
  negative_tag: broke